#include "TWO_DOF_PID.h"

TWO_DOF_PID_PARAM ROLL_PITHC_PID_GAIN_0;
ROLL_PITHC_PID_GAIN_0.ffGain = 0;
ROLL_PITHC_PID_GAIN_0.pGain = 0;
ROLL_PITHC_PID_GAIN_0.iGain = 0;
ROLL_PITHC_PID_GAIN_0.dGain = 0;
ROLL_PITHC_PID_GAIN_0.upperControlLimit = 100;
ROLL_PITHC_PID_GAIN_0.lowerControlLimit = 0;